SELECT VEHICLE.VIN,
  VEHICLE.VEHICLEID,
  VEHICLE.LICNO,
  WORKORDER.ACTCOMPDATETIME,
  WORKORDER.EXPCOMDATETIME
FROM VEHSERVICE
INNER JOIN WORKORDER
ON WORKORDER.WOID = VEHSERVICE.WOID
INNER JOIN VEHICLE
ON VEHICLE.VEHICLEID       = WORKORDER.VEHICLEID
WHERE WORKORDER.WODATETIME > '16-NOV-2015 00:00'
