SELECT VEHICLE.VEHICLEID,
  VEHSERVICE.SERVICEID,
  WORKORDER.WOID,
  WORKORDER.WODATETIME
FROM VEHSERVICE
INNER JOIN WORKORDER
ON WORKORDER.WOID = VEHSERVICE.WOID
INNER JOIN VEHICLE
ON VEHICLE.VEHICLEID = WORKORDER.VEHICLEID
