SELECT CUSTOMER.LNAME,
  CUSTOMER.FNAME,
  CUSTOMER.STATE,
  VEHICLE.MANUFACTURER,
  VEHICLE.MAKE,
  VEHICLE.MODEL,
  VEHICLE.YEAR
FROM CUSTOMER
INNER JOIN VEHICLE
ON CUSTOMER.CUSTID    = VEHICLE.CUSTID
WHERE CUSTOMER.STATE <> 'WI'
