SELECT VEHICLE.VEHICLEID,
  VEHICLE.LICNO,
  SERVICE.SERVICEID
FROM VEHICLE
INNER JOIN WORKORDER
ON VEHICLE.VEHICLEID = WORKORDER.VEHICLEID
INNER JOIN VEHSERVICE
ON WORKORDER.WOID = VEHSERVICE.WOID
INNER JOIN SERVICE
ON SERVICE.SERVICEID = VEHSERVICE.SERVICEID
INNER JOIN CUSTOMER
ON CUSTOMER.CUSTID       = VEHICLE.CUSTID
WHERE (SERVICE.SERVICEID = 'S1')
OR (SERVICE.SERVICEID    = 'S3')
