SELECT AVG(DISTINCT INVOICE.TOTAL),
  VEHICLE.VEHICLEID
FROM INVOICE
INNER JOIN CUSTOMER
ON CUSTOMER.CUSTID = INVOICE.CUSTID
INNER JOIN VEHICLE
ON CUSTOMER.CUSTID = VEHICLE.CUSTID
GROUP BY VEHICLE.VEHICLEID]
